#!/bin/bash

username="alui2" # Change this to your user name
server="citrisdance"

sftp $username@$server.soe.ucsc.edu <<EOF
  cd advBayesComputing/hw/hw2/code/R/output
  get out.RData
EOF

mv out.RData output/out.RData
