#!/bin/bash

username="alui2" # Change this to your user name
server="citrisdance"


#ssh $username@$server.soe.ucsc.edu <<EOF
#  cd advBayesComputing/hw/hw2/code/R
#  git pull
#  
#  Rscript gp_sim.R
#EOF

ssh $username@$server.soe.ucsc.edu <<EOF
  cd advBayesComputing/hw/hw2/code/R
  git pull
EOF

ssh -t $username@$server.soe.ucsc.edu "cd advBayesComputing/hw/hw2/code/R; bash"
